all:
	cd ..; make Memoria

base deadlock:
	cp ./tuki-pruebas/BASE.config ./memoria.config; ./memoria.out

error:
	cp ./tuki-pruebas/ERROR.config ./memoria.config; ./memoria.out

memoria:
	cp ./tuki-pruebas/MEMORIA.config ./memoria.config; ./memoria.out

fs:
	cp ./tuki-pruebas/FILESYSTEM.config ./memoria.config; ./memoria.out
