all:
	cd ..; make Kernel

base:
	cp ./tuki-pruebas/BASE.config ./kernel.config; ./kernel.out

deadlock:
	cp ./tuki-pruebas/DEADLOCK.config ./kernel.config; ./kernel.out

error:
	cp ./tuki-pruebas/ERROR.config ./kernel.config; ./kernel.out

ejemplo:
	cp ./tuki-pruebas/EJEMPLO.config ./kernel.config; ./kernel.out